Meta: Update makem.sh

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -47,21 +47,19 @@ jobs:
 
     - uses: actions/checkout@v2
 
-    - name: Install sandbox script
-      run: |
-        curl -o $GITHUB_WORKSPACE/emacs-sandbox.sh \
-          https://raw.githubusercontent.com/alphapapa/emacs-sandbox.sh/master/emacs-sandbox.sh
-        chmod +x $GITHUB_WORKSPACE/emacs-sandbox.sh
-        echo ::add-path::$GITHUB_WORKSPACE
-        echo ::set-env name=SANDBOX_DIR::$(mktemp -d)
-
     - name: Initialize sandbox
-      run: ./makem.sh -vv --sandbox-dir=$SANDBOX_DIR --auto-install --install package-lint
+      run: |
+        SANDBOX_DIR=$(mktemp -d) || exit 1
+        echo ::set-env name=SANDBOX_DIR::$SANDBOX_DIR
+        ./makem.sh -vv --sandbox-dir=$SANDBOX_DIR --install-deps --install-linters
 
     # The "all" rule is not used, because it treats compilation warnings
     # as failures, so linting and testing are run as separate steps.
 
     - name: Lint
+      # NOTE: Uncomment this line to treat lint failures as passing
+      #       so the job doesn't show failure.
+      # continue-on-error: true
       run: ./makem.sh -vv --sandbox-dir=$SANDBOX_DIR lint
 
     - name: Test
